# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('current', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('monitorpic', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('robot', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('sound', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinates', models.FloatField(blank=True, null=True)),
                ('y_coordinates', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, help_text='请输入工位名字.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='工位描述.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('voltage', models.TextField(blank=True, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.Station')),
            ],
        ),
        migrations.CreateModel(
            name='WeldpoolPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('weldpoolPic', models.TextField(blank=True, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.Station')),
            ],
        ),
        migrations.AddField(
            model_name='sound',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.Station'),
        ),
        migrations.AddField(
            model_name='robot',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.Station'),
        ),
        migrations.AddField(
            model_name='monitorpic',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.Station'),
        ),
        migrations.AddField(
            model_name='current',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Management.Station'),
        ),
    ]
